# docker-compose for test developpement
# don't deploy it in the production server

services:
  lssm-db:
    container_name: lssm-db
    image: mdillon/postgis
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=lssm
      - POSTGRES_USER=lssm
      - POSTGRES_PASSWORD=lssm
      - PGDATA=/var/lib/lssm-db/data
    volumes:
      - ./packages/lssm-init-db:/docker-entrypoint-initdb.d

  aws-local:
    container_name: localstack_main
    image: localstack/localstack:latest
    environment:
      - AWS_DEFAULT_REGION=eu-west-3
      - EDGE_PORT=4566
      - SERVICES=s3,sqs
      - DATA_DIR=/tmp/localstack
    ports:
      - 4566:4566
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./aws:/docker-entrypoint-initaws.d"
