services:
  lssm-db:
    image: postgres:14
    environment:
      POSTGRES_DB: lssm
      POSTGRES_USER: lssm
      POSTGRES_PASSWORD: lssm
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5442"
  coviflex-db:
    container_name: coviflex-db
    image: mdillon/postgis
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=coviflex
      - POSTGRES_USER=coviflex
      - POSTGRES_PASSWORD=coviflex
      - PGDATA=/var/lib/coviflex-db/data
    volumes:
      - ./coviflex-init-db:/docker-entrypoint-initdb.d

  # For later
  # server:
  #   build:
  #     context: ./app/server
  #     dockerfile: Dockerfile
  #   restart: always
  #   environment:
  #     - DATABASE_HOST=postgres
  #     - DATABASE_PORT=5432
  #     - DATABASE_NAME=myapp
  #     - DATABASE_USER=admin
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./src:/app/src:ro
  #     - ./libs:/app/libs:ro

volumes:
  postgres-data:
